# Generated by Django 3.2.6 on 2021-08-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_applicant_applied_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(upload_to='applicant_cv'),
        ),
    ]
