# Generated by Django 3.2.6 on 2021-08-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_applicant_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
