# Generated by Django 3.2.6 on 2021-08-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_delete_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
